name: Phu Tang Photography
favicon: null
layout_spectrum: 0.8318403963930905
typography_spectrum: 0.2036929656751454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7519032822456211
  lightness: 0.670411390485242
  saturation: 0.7019763090647757
  rhythmicContrast: 0.6193726602941751
purpose: []
