name: Phu Tang Photography
favicon: null
layout_spectrum: 0.8318403963930905
typography_spectrum: 0.2036929656751454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#030303'
    - '#afaaa7'
    - '#698b00'
    - '#9f5203'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.6193726602941751
purpose: []
